language: minimal
dist: xenial
services:
  - docker
before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/master/bin/travis-bootstrap | bash
  - cip before-install
install:
  - cip diag
  - cip install
script:
  - cip script
jobs:
  include:
    - env: CIP_TAG=static
    - env: CIP_TAG=5.30-bullseye
    - env: CIP_TAG=5.28-bullseye
    - env: CIP_TAG=5.26-bullseye
    - env: CIP_TAG=5.24-bullseye
    - env: CIP_TAG=5.22-bullseye
    - env: CIP_TAG=5.20-bullseye
cache:
  directories:
    - "$HOME/.cip"


